# version: '3'

services:
  db:
    image: mariadb:11.6
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2-fpm
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    volumes:
      - phpmyadmin:/var/www/html
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  certbot:
    image: certbot/certbot:v3.0.1
    restart: on-failure
    volumes:
      - certbot:/etc/letsencrypt
      - wordpress:/var/www/wordpress
      - ./conf/nginx:/etc/nginx/conf.d:rw # 필요한가?
    command: certonly --webroot --reinstall --agree-tos --email ${EMAIL} --no-eff-email -d ${DOMAIN} -w /var/www/wordpress

  webserver:
    depends_on:
      - phpmyadmin
      - wordpress
    image: nginx:1.27
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot:/etc/letsencrypt
      - wordpress:/var/www/wordpress
      - phpmyadmin:/var/www/html
      - ./conf/nginx:/etc/nginx/conf.d:ro
    networks:
      - app-network

volumes:
  certbot:
  mariadb:
  phpmyadmin:
  wordpress:

networks:
  app-network:
    driver: bridge
