# version: '3'

services:
  db:
    image: mariadb:11.6
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2-fpm
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=https://${DOMAIN}/pma/
    volumes:
      - phpmyadmin:/var/www/html
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - wordpress:/var/www/html
      - phpmyadmin:/var/www/phpmyadmin
    networks:
      - app-network
    env_file: .env

volumes:
  mariadb:
  phpmyadmin:
  wordpress:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
