# version: '3'

services:
  db:
    image: mariadb:10.11
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1-fpm-alpine
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    volumes:
      - phpmyadmin:/var/www/html
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7.1-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
      - phpmyadmin
    image: nginx:1.27.3-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - wordpress:/var/www/wordpress
      - phpmyadmin:/var/www/phpmyadmin
      - ./conf/nginx:/etc/nginx/conf.d:ro
    networks:
      - app-network

volumes:
  mariadb:
  wordpress:
  phpmyadmin:

networks:
  app-network:
    driver: bridge
