# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gychoi <gychoi@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/19 14:57:59 by gychoi            #+#    #+#              #
#    Updated: 2024/03/19 14:58:03 by gychoi           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.8"
name: inception

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      network:
        ipv4_address: "172.21.42.40"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "true"]
      interval: 3s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"
    networks:
      network:
        ipv4_address: "172.21.42.41"
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        CERT_PATH: ${CERTS_}
        DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      network:
        ipv4_address: "172.21.42.42"
    restart: on-failure

volumes:
  mariadb:
    driver_opts:
      type: none
      device: ${MARIADB_PATH}
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: ${WORDPRESS_PATH}
      o: bind

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.42.0/24"
          gateway: "172.21.42.1"
