# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gychoi <gychoi@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/19 14:57:59 by gychoi            #+#    #+#              #
#    Updated: 2024/03/19 14:58:03 by gychoi           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.8"
name: inception

services:
  mariadb:
    container_name: mariadb
    # build:
    #   context: ./requirements/mariadb
    #   dockerfile: Dockerfile
    #   labels:
    #     - "com.example.label=mariadb"
    image: yobasystems/alpine-mariadb
    env_file:
      - .test_env
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      network:
        ipv4_address: "172.42.42.40"
    restart: on-failure:3

  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-fpm
    depends_on:
      - mariadb
      # mariadb:
      #   condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s
    env_file:
      - .test_env
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"
    networks:
      network:
        ipv4_address: "172.42.42.41"
    restart: on-failure:3

  nginx:
    container_name: nginx
    image: yobasystems/alpine-nginx
    depends_on:
      - wordpress
      # wordpress:
      #   condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress:/var/www/html
    ports:
      - target: "80"
        published: "8080"
        host_ip: "127.0.0.1"
        protocol: "tcp"

    networks:
      network:
        ipv4_address: "172.42.42.42"
    restart: on-failure:3

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_PATH}
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_PATH}
      o: bind

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.42.42.0/24"
          gateway: "172.42.42.1"
