version: "3.8"
name: inception

services:
  mariadb:
    container_name: mariadb
    # build:
    #   context: ./requirements/mariadb
    #   dockerfile: Dockerfile
    #   labels:
    #     - "com.example.label=mariadb"
    image: yobasystems/alpine-mariadb
    env_file:
      - .test_env
    expose:
      - "3306"
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-fpm
    depends_on:
      - mariadb
    links:
      - mariadb
    env_file:
      - .test_env
    expose:
      - "9000"
    restart: always
    volumes:
      - wordpress:/var/www/html

  nginx:
    container_name: nginx
    image: yobasystems/alpine-nginx
    depends_on:
      - wordpress
    links:
      - wordpress
    ports:
      - "4444:80"
    restart: always
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress:/var/www/html

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_PATH}
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_PATH}

networks:
  net-inception:
    driver: bridge
