// i18next 초기화 설정
i18next.init({
  resources: {
    en: {
      translation: {
        'recent-history': 'Recent History',
        'friend-request': 'Friend Request',
        'friends': 'Friends',
        'choose-photo': 'Choose a photo for your profile',
        'rate': 'Rate',
        'win': 'Win',
        'loss': 'Loss',
        '2fa-option': '2FA Authentication Options',
        'language': 'Select Language',
        'change-password-guide': 'Change Password',
        'change-password': 'Change Password',
        'unsubscribe-guide': 'Unsubscribe',
        'unsubscribe': 'Unsubscribe',
        'confirm2FAModalLabel': '2FA Authentication Confirmation',
        'confirm-2fa-modal-message': 'Do you want to proceed with 2FA authentication?',
        'confirm-2fa-modal-cancel': 'Cancel',
        'confirm-2fa-modal-continue': 'Continue',
        'codeInputModalLabel': 'Enter Authentication Code',
        'code-input-modal-label-code': 'Authentication Code',
        'codeInput': 'Enter your code',
        'timer': 'Remaining time: 05:00',
        'code-input-modal-label-confirm': 'Confirm Code',
        'code-input-modal-label-resend': 'Resend Code',
        'lang-ko': 'Korean',
        'lang-en': 'English',
        'lang-fr': 'French',
        'changePasswordModalLabel': 'Change Password',
        'change-password-modal-current': 'Current Password',
        'change-password-modal-new': 'New Password',
        'change-password-modal-new-confirm': 'Confirm New Password',
        'change-password-modal-cancel': 'Cancel',
        'change-password-modal-change': 'Change',
        'confirmDeletionModalLabel': 'Confirm Account Deletion',
        'confirm-deletion-modal-content': 'Are you sure you want to delete your account? This action cannot be undone.',
        'confirm-deletion-modal-cancel': 'Cancel',
        'confirm-deletion-modal-confirm': 'Confirm',
        'passwordConfirmModalLabel': 'Password Confirmation',
        'password-confirm-form-content': 'Please enter your password',
        'password-confirm-form-input': 'Password',
        'password-confirm-form-confirm': 'Confirm',
        'pong': 'PONG',
        'classic': 'CLASSIC',
        'player1': 'PLAYER 1',
        'player2': 'PLAYER 2',
        'gameSettingModalLabel': 'Game Setting',
        'player2-label': 'Player 2',
        'player-name': 'Name',
        'mode': 'mode',
        'normal-label' : 'normal',
        'speed-label': 'speed',
        'object-label': 'object',
        'startGameButton' : 'START',
        'scoreModalLabel': 'SCORE',
        'win-label': 'WIN',
        'lose-label': 'LOSE',
        'score-player2': 'Player 2',
        'save-score' : 'SAVE SCORE',
        'email2faModalLabel': 'Email Verification',
        'email-input-label': 'Email Address',
        'emailInput': 'Enter your email (e.g., name@example.com)',
        'send-verification-code-button': 'Send Code',
        'verification-code-label': 'Verification Code',
        'verificationCodeInput': 'Enter verification code',
        'submit-verification-code-button': 'Verify Code',
        'tournament-pong': 'PONG',
        'tournament-header': 'TOURNAMENT',
        'tournament-player1': 'PLAYER 1',
        'tournament-player2': 'PLAYER 2',
        'tournamentSettingModalLabel': 'TOURNAMENT GAME SETTING',
        't-player1-label': 'player 1',
        "player1-name": "name",
        't-player2-label': 'player 2',
        "player2-name": "name",
        't-player3-label': 'player 3',
        "player3-name": "name",
        't-player4-label': 'player 4',
        "player4-name": "name",
        't-mode': 'mode',
        't-normal-label': 'normal',
        't-speed-label': 'speed',
        't-object-label': 'object',
        'tournamentRoundModalLabel' :'TOURNAMENT ROUND {{round}}',
        'round-player1' : 'PLAYER 1',
        'round-player2' : 'PLAYER 2',
        'round-content': 'Are you ready?',
        'startRoundButton': 'START',
        'tournamentWinnerModalLabel' : 'TOURNAMENT WINNER!',
        'tournament_player' : 'Player',
        'restartGameButton': 'OK'
      }
    },
    ko: {
      translation: {
        "recent-history": "최근 역사",
        "friend-request": "친구 요청",
        "friends": "친구들",
        "choose-photo": "프로필 사진 선택",
        "rate": "승률",
        "win": "승리",
        "loss": "패배",
        "2fa-option": "2단계 인증 옵션",
        "language": "언어 선택",
        "change-password-guide": "비밀번호 변경",
        "change-password": "비밀번호 변경",
        "unsubscribe-guide": "구독 취소",
        "unsubscribe": "구독 취소",
        "confirm2FAModalLabel": "2단계 인증 확인",
        "confirm-2fa-modal-message": "2단계 인증을 진행하시겠습니까?",
        "confirm-2fa-modal-cancel": "취소",
        "confirm-2fa-modal-continue": "계속",
        "codeInputModalLabel": "인증 코드 입력",
        "code-input-modal-label-code": "인증 코드",
        "codeInput": "코드를 입력하세요",
        "timer": "남은 시간: 05:00",
        "code-input-modal-label-confirm": "코드 확인",
        'code-input-modal-label-resend': '코드 재전송',
        "lang-ko": "한국어",
        "lang-en": "영어",
        "lang-fr": "프랑스어",
        "changePasswordModalLabel": "비밀번호 변경",
        "change-password-modal-current": "현재 비밀번호",
        "change-password-modal-new": "새 비밀번호",
        "change-password-modal-new-confirm": "새 비밀번호 확인",
        "change-password-modal-cancel": "취소",
        "change-password-modal-change": "변경하기",
        "confirmDeletionModalLabel": "회원 탈퇴 확인",
        "confirm-deletion-modal-content": "정말로 계정을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        "confirm-deletion-modal-cancel": "취소",
        "confirm-deletion-modal-confirm": "확인",
        "passwordConfirmModalLabel": "비밀번호 확인",
        "password-confirm-form-content": "비밀번호를 입력하세요",
        "password-confirm-form-input": "비밀번호",
        "password-confirm-form-confirm": "확인",
        'pong': '퐁',
        'classic': '클래식',
        'player1': '플레이어 1',
        'player2': '플레이어 2',
        'gameSettingModalLabel': '게임 설정',
        'player2-label': '플레이어 2',
        'player-name': '이름',
        'mode': '모드',
        'normal-label': '일반',
        'speed-label': '스피드',
        'object-label': '오브젝트',
        'startGameButton' : '시작',
        'scoreModalLabel': '점수',
        'win-label': '승리',
        'lose-label': '패배',
        'score-player2': '플레이어 2',
        'save-score': '점수 저장',
        'email2faModalLabel': '이메일 인증',
        'email-input-label': '이메일 주소',
        'emailInput': '이메일 입력 (예: name@example.com)',
        'send-verification-code-button': '인증 코드 전송',
        'verification-code-label': '인증 코드',
        'verificationCodeInput': '인증 코드 입력',
        'submit-verification-code-button': '인증 코드 확인',
        'tournament-pong': '퐁',
        'tournament-header': '토너먼트',
        'tournament-player1': '플레이어 1',
        'tournament-player2': '플레이어 2',
        'tournamentSettingModalLabel': '토너먼트 게임 설정',
        't-player1-label': '플레이어 1',
        'player1-name': '이름',
        't-player2-label': '플레이어 2',
        'player2-name': '이름',
        't-player3-label': '플레이어 3',
        'player3-name': '이름',
        't-player4-label': '플레이어 4',
        'player4-name': '이름',
        't-mode': '모드',
        't-normal-label': '일반',
        't-speed-label': '스피드',
        't-object-label': '오브젝트',
        'tournamentRoundModalLabel': '토너먼트 라운드 {{round}}',
        'round-player1': '플레이어 1',
        'round-player2': '플레이어 2',
        'round-content': '준비되셨나요?',
        'startRoundButton' : '시작',
        'tournamentWinnerModalLabel' : '토너먼트 우승자!',
        'tournament_player' : '플레이어',
        'restartGameButton' : '확인'
      }
    },
    fr: {
      translation: {
        "recent-history": "Histoire Récente",
        "friend-request": "Demande d'Ami",
        "friends": "Amis",
        "choose-photo": "Choisir une photo pour votre profil",
        "rate": "Taux",
        "win": "Gagner",
        "loss": "Perte",
        "2fa-option": "Options d'authentification 2FA",
        "language": "Choisir la Langue",
        "change-password-guide": "Changer le Mot de Passe",
        "change-password": "Changer le Mot de Passe",
        "unsubscribe-guide": "Se Désabonner",
        "unsubscribe": "Se Désabonner",
        "confirm2FAModalLabel": "Confirmation d'authentification 2FA",
        "confirm-2fa-modal-message": "Voulez-vous procéder à l'authentification 2FA?",
        "confirm-2fa-modal-cancel": "Annuler",
        "confirm-2fa-modal-continue": "Continuer",
        "codeInputModalLabel": "Entrez le code d'authentification",
        "code-input-modal-label-code": "Code d'authentification",
        "codeInput": "Entrez votre code",
        "timer": "Temps restant : 05:00",
        "code-input-modal-label-confirm": "Confirmer le code",
        'code-input-modal-label-resend': 'Renvoyer le code',
        "lang-ko": "Coréen",
        "lang-en": "Anglais",
        'lang-fr': 'Français',
        "changePasswordModalLabel": "Changer le mot de passe",
        "change-password-modal-current": "Mot de passe actuel",
        "change-password-modal-new": "Nouveau mot de passe",
        "change-password-modal-new-confirm": "Confirmer le nouveau mot de passe",
        "change-password-modal-cancel": "Annuler",
        "change-password-modal-change": "Changer",
        "confirmDeletionModalLabel": "Confirmation de la suppression du compte",
        "confirm-deletion-modal-content": "Êtes-vous sûr de vouloir supprimer votre compte? Cette action est irréversible.",
        "confirm-deletion-modal-cancel": "Annuler",
        "confirm-deletion-modal-confirm": "Confirmer",
        "passwordConfirmModalLabel": "Confirmation du mot de passe",
        "password-confirm-form-content": "Veuillez entrer votre mot de passe",
        "password-confirm-form-input": "Mot de passe",
        "password-confirm-form-confirm": "Confirmer",
        'pong': 'PONG',
        'classic': 'CLASSIQUE',
        'player1': 'JOUEUR 1',
        'player2': 'JOUEUR 2',
        'gameSettingModalLabel': 'Paramètres du jeu',
        'player2-label': 'Joueur 2',
        'player-name': 'Nom',
        'mode': 'mode',
        'normal-label': 'normal',
        'speed-label': 'vitesse',
        'object-label': 'objet',
        'startGameButton': 'COMMENCER',
        'scoreModalLabel': 'SCORE',
        'win-label': 'GAGNER',
        'lose-label': 'PERDRE',
        'score-player2': 'Joueur 2',
        'save-score': 'ENREGISTRER LE SCORE',
        'email2faModalLabel': 'Vérification d\'email',
        'email-input-label': 'Adresse e-mail',
        'emailInput': 'Entrez votre e-mail (par ex., name@example.com)',
        'send-verification-code-button': 'Envoyer le code',
        'verification-code-label': 'Code de vérification',
        'verificationCodeInput': 'Entrez le code de vérification',
        'submit-verification-code-button': 'Vérifier le code',
        'tournament-pong': 'PONG',
        'tournament-header': 'TOURNOI',
        'tournament-player1': 'JOUEUR 1',
        'tournament-player2': 'JOUEUR 2',
        'tournamentSettingModalLabel': 'Configuration du jeu de tournoi',
        't-player1-label': 'joueur 1',
        'player1-name': 'nom',
        't-player2-label': 'joueur 2',
        'player2-name': 'nom',
        't-player3-label': 'joueur 3',
        'player3-name': 'nom',
        't-player4-label': 'joueur 4',
        'player4-name': 'nom',
        't-mode': 'mode',
        't-normal-label': 'normal',
        't-speed-label': 'vitesse',
        't-object-label': 'objet',
        'tournamentRoundModalLabel': 'TOURNOI ROUND {{round}}',
        'round-player1': 'JOUEUR 1',
        'round-player2': 'JOUEUR 2',
        'round-content': 'Êtes-vous prêt ?',
        'startRoundButton' : 'COMMENCER',
        'tournamentWinnerModalLabel' : 'VAINQUEUR DU TOURNOI !',
        'tournament_player' : 'Joueur',
        'restartGameButton': 'OK'
      }
    }
  },
  fallbackLng: "en",
  debug: true
});


// 기존의 함수들은 변경 없음

// 언어 변경 함수
export function changeLanguage(languageCode) {
  // 현재 설정된 언어와 같은 경우 변경하지 않음
  if (i18next.language === languageCode) {
    return;
  }

  i18next.changeLanguage(languageCode, (err, t) => {
    if (err) return console.error(err);
    updateContent();
  });
}

// 언어명을 언어 코드로 변환하는 함수
function mapLanguageToCode(language) {
  const languageMap = {
    korean: 'ko',
    english: 'en',
    french: 'fr'
  };
  return languageMap[language.toLowerCase()] || 'en'; // 기본값으로 'en' 설정
}


// 페이지 콘텐츠 업데이트
export function updateContent() {
  document.getElementById("recent-history").innerHTML = i18next.t("recent-history");
  document.getElementById("friend-request").innerHTML = i18next.t("friend-request");
  document.getElementById("friends").innerHTML = i18next.t("friends");
  document.getElementById("rate").innerHTML = i18next.t("rate");
  document.getElementById("win").innerHTML = i18next.t("win");
  document.getElementById("loss").innerHTML = i18next.t("loss");
  document.getElementById("choose-photo").innerHTML = i18next.t("choose-photo");
  document.getElementById("2fa-option").innerHTML = i18next.t("2fa-option");
  document.getElementById("language").innerHTML = i18next.t("language");
  document.getElementById("change-password-guide").innerHTML = i18next.t("change-password-guide");
  document.getElementById('change-password').innerHTML = i18next.t('change-password');
  document.getElementById('unsubscribe-guide').innerHTML = i18next.t('unsubscribe-guide');
  document.getElementById('unsubscribe').innerHTML = i18next.t('unsubscribe');
  document.getElementById('lang-ko').innerHTML = i18next.t('lang-ko');
  document.getElementById("lang-en").innerHTML = i18next.t("lang-en");
  document.getElementById('lang-fr').innerHTML = i18next.t('lang-fr');
}