#!/bin/bash

cleanup() {
	echo "terminating SSH session..."
	kill $SSH_PID
	exit
}

trap 'cleanup' SIGINT

ssh -L 59000:localhost:5901 -C -N -X inception &
SSH_PID=$!

echo "connecting to vnc..."

open -a ~/Applications/Firefox\ Nightly.app -g vnc://localhost:59000

wait $SSH_PID
